package demowebshop.fileutility;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
public class Readproperties {
	 FileInputStream fis;
	 public String fetchproperty(String key) {
		 try {
			 fis= new FileInputStream("./src/test/resources/shop.properties"); 
		 }
		 catch (FileNotFoundException e) { 
			 //Todo auto-generated catch block
			 e.printStackTrace();
			
		 }
		 Properties pobj= new Properties();
		 try {
			 pobj.load(fis);
		 }
		 catch(IOException e) {
			 //todoautogenerated catch block
			 e.printStackTrace();
		 }
		 String data =pobj.getProperty(key);
		 return data;
			
		 
		 
		 
	 }


}
